server {
    listen 8080;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /cs/ {
        proxy_pass https://www.cnb.cz;
        proxy_set_header Host www.cnb.cz;
        proxy_ssl_server_name on;
    }
}
